import { DailyContract } from './splurge-types';

const CONTRACT_POOL: Omit<DailyContract, 'status'>[] = [

  // ── TRANSPORT (3) ──────────────────────────────────────────────────────
  {
    id: 'c-transport-1',
    title: 'The Grab Boycott',
    subtitle: 'Ride your own bike or walk. No ride-hailing today. Your legs still work.',
    reward: 15,
    penalty: -15,
    iconType: 'Bike',
  },
  {
    id: 'c-transport-2',
    title: 'The Pedestrian Protocol',
    subtitle: 'Any trip under 1km — walk it. No excuses, no apps, no shortcuts.',
    reward: 10,
    penalty: -10,
    iconType: 'Footprints',
  },
  {
    id: 'c-transport-3',
    title: 'Bus Mode Activated',
    subtitle: 'Take public transport for at least one trip instead of calling a ride.',
    reward: 15,
    penalty: -15,
    iconType: 'Bus',
  },

  // ── FOOD & DRINKS (10) ─────────────────────────────────────────────────
  {
    id: 'c-food-1',
    title: 'Caffeine Fast',
    subtitle: 'Skip the café walk-in. G7 instant or water only today.',
    reward: 10,
    penalty: -10,
    iconType: 'Coffee',
  },
  {
    id: 'c-food-2',
    title: 'Boba Defiance',
    subtitle: 'Walk past the milk tea shop. Do not open the app either.',
    reward: 10,
    penalty: -10,
    iconType: 'CupSoda',
  },
  {
    id: 'c-food-3',
    title: 'Hawker Reserve',
    subtitle: 'Cook at home for at least one meal instead of ordering in.',
    reward: 15,
    penalty: -15,
    iconType: 'Utensils',
  },
  {
    id: 'c-food-4',
    title: 'Delivery Blackout',
    subtitle: 'No GrabFood, ShopeeFood, or any delivery apps today. Full home-cook day.',
    reward: 20,
    penalty: -20,
    iconType: 'Pizza',
  },
  {
    id: 'c-food-5',
    title: 'Water Only Mode',
    subtitle: 'Only water and free drinks today. No purchased beverages at all.',
    reward: 15,
    penalty: -15,
    iconType: 'Droplets',
  },
  {
    id: 'c-food-6',
    title: 'Energy Drink Ban',
    subtitle: 'No Red Bull, Monster, or Sting today. Your cortisol and your wallet both need a break.',
    reward: 10,
    penalty: -10,
    iconType: 'Zap',
  },
  {
    id: 'c-food-7',
    title: 'Pack Lunch Protocol',
    subtitle: 'Bring food from home for lunch. Not Grab. Not the canteen downstairs.',
    reward: 15,
    penalty: -15,
    iconType: 'Package',
  },
  {
    id: 'c-food-8',
    title: 'The Beer Pause',
    subtitle: 'Skip the bia hơi session tonight. Stay home. Your streak stays alive.',
    reward: 20,
    penalty: -20,
    iconType: 'Beer',
  },
  {
    id: 'c-food-9',
    title: 'The Pantry Raid',
    subtitle: 'Cook a full meal using only what you already have at home. Zero top-ups.',
    reward: 20,
    penalty: -20,
    iconType: 'Home',
  },
  {
    id: 'c-food-10',
    title: 'Snack Drawer Only',
    subtitle: 'Eat snacks you already own. No new snack purchases of any kind today.',
    reward: 10,
    penalty: -10,
    iconType: 'Apple',
  },

  // ── ONLINE SHOPPING (5) ────────────────────────────────────────────────
  {
    id: 'c-shop-1',
    title: 'The Shopee Shield',
    subtitle: 'Zero flash-sale checkouts today. Browse if you must — but your cart stays full.',
    reward: 20,
    penalty: -20,
    iconType: 'ShoppingCart',
  },
  {
    id: 'c-shop-2',
    title: 'TikTok Shop Lockdown',
    subtitle: 'No purchases from TikTok Shop today. Watch the videos. Skip the checkout.',
    reward: 15,
    penalty: -15,
    iconType: 'Smartphone',
  },
  {
    id: 'c-shop-3',
    title: 'Cart Freeze Protocol',
    subtitle: 'Nothing leaves your saved carts today. No checkouts from any platform.',
    reward: 20,
    penalty: -20,
    iconType: 'Lock',
  },
  {
    id: 'c-shop-4',
    title: 'Wishlist-Only Mode',
    subtitle: 'See something you want? Add to wishlist. Do NOT buy it today. Future you will decide.',
    reward: 15,
    penalty: -15,
    iconType: 'Star',
  },
  {
    id: 'c-shop-5',
    title: 'Flash Sale Immunity',
    subtitle: 'A time-limited deal appeared. You closed the tab. You win.',
    reward: 20,
    penalty: -20,
    iconType: 'Timer',
  },

  // ── DIGITAL & GAMING (5) ───────────────────────────────────────────────
  {
    id: 'c-digital-1',
    title: 'Gacha Discipline',
    subtitle: 'No gacha pulls, loot boxes, or in-app purchases in any game today.',
    reward: 20,
    penalty: -20,
    iconType: 'Gamepad2',
  },
  {
    id: 'c-digital-2',
    title: 'App Store Hold',
    subtitle: 'No paid app downloads or in-app purchases. Free-to-play only today.',
    reward: 15,
    penalty: -15,
    iconType: 'Smartphone',
  },
  {
    id: 'c-digital-3',
    title: 'Sub Freeze',
    subtitle: "No signing up for new subscriptions today. You probably don't need it.",
    reward: 15,
    penalty: -15,
    iconType: 'Wifi',
  },
  {
    id: 'c-digital-4',
    title: 'No Social Commerce',
    subtitle: 'You saw an ad and wanted to buy. You closed the app instead. That is discipline.',
    reward: 15,
    penalty: -15,
    iconType: 'Tv',
  },
  {
    id: 'c-digital-5',
    title: 'Steam / Console Hold',
    subtitle: 'No game purchases on any platform today. Your backlog is already full.',
    reward: 20,
    penalty: -20,
    iconType: 'Gamepad2',
  },

  // ── CONVENIENCE & OUT-OF-HOME (3) ──────────────────────────────────────
  {
    id: 'c-conv-1',
    title: 'Circle K Blackout',
    subtitle: "Skip the convenience store impulse run. Whatever you think you need — you have it at home.",
    reward: 10,
    penalty: -10,
    iconType: 'Store',
  },
  {
    id: 'c-conv-2',
    title: 'Pre-Game Protocol',
    subtitle: 'Eat at home before going out. Arrive full. Spend dramatically less.',
    reward: 15,
    penalty: -15,
    iconType: 'Home',
  },
  {
    id: 'c-conv-3',
    title: 'Eat Before You Meet',
    subtitle: 'Have a proper meal before any social event so you order less when you get there.',
    reward: 10,
    penalty: -10,
    iconType: 'Utensils',
  },

  // ── SOCIAL SPENDING (3) ────────────────────────────────────────────────
  {
    id: 'c-social-1',
    title: 'The Social Redirect',
    subtitle: 'Suggest a free hangout — a park, a walk, or yours — instead of a café or bar.',
    reward: 20,
    penalty: -20,
    iconType: 'Users',
  },
  {
    id: 'c-social-2',
    title: 'Karaoke Hold',
    subtitle: 'Skip the karaoke session tonight. Your wallet is already singing.',
    reward: 20,
    penalty: -20,
    iconType: 'Mic',
  },
  {
    id: 'c-social-3',
    title: 'The Maxi-Water Rule',
    subtitle: 'At any bar or restaurant today — only water. Order food, skip the drinks menu.',
    reward: 15,
    penalty: -15,
    iconType: 'Droplets',
  },

  // ── HIGH-STAKES DISCIPLINE (4) ─────────────────────────────────────────
  {
    id: 'c-hard-1',
    title: 'The Gym Bet',
    subtitle: 'Work out instead of spending money on entertainment to feel better. Earn it physically.',
    reward: 20,
    penalty: -20,
    iconType: 'Dumbbell',
  },
  {
    id: 'c-hard-2',
    title: 'Zero Day Protocol',
    subtitle: 'Zero discretionary spending today. Essentials only. This is the final boss.',
    reward: 25,
    penalty: -25,
    iconType: 'Target',
  },
  {
    id: 'c-hard-3',
    title: 'The 24h Wait Rule',
    subtitle: 'Every purchase urge today gets a mandatory 24-hour delay. Vault it or forget it.',
    reward: 25,
    penalty: -25,
    iconType: 'Clock',
  },
  {
    id: 'c-hard-4',
    title: 'The Vault-First Rule',
    subtitle: 'Every non-essential purchase urge goes to the Vault first today. No direct buying allowed.',
    reward: 25,
    penalty: -25,
    iconType: 'Lock',
  },
];

export function generateDailyContracts(): DailyContract[] {
  const shuffled = [...CONTRACT_POOL].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 4).map((c) => ({ ...c, status: 'available' as const }));
}
